export class TacticalMap{
 constructor(canvas,{world,getShip,getTraffic,navigation,onDestination}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.world=world;this.getShip=getShip;this.getTraffic=getTraffic;this.navigation=navigation;this.onDestination=onDestination;this.zoom=.22;this.cx=getShip().x;this.cy=getShip().y;this.drag=null;this.hover=null;this.selected=null;this.pointer={x:0,y:0};this.bind()}
 bind(){const c=this.canvas;c.addEventListener('wheel',e=>{e.preventDefault();const before=this.toWorld(e.offsetX,e.offsetY);this.zoom=Math.max(.06,Math.min(1.8,this.zoom*Math.exp(-e.deltaY*.0012)));const after=this.toWorld(e.offsetX,e.offsetY);this.cx+=before.x-after.x;this.cy+=before.y-after.y},{passive:false});c.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,cx:this.cx,cy:this.cy};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{this.pointer={x:e.offsetX,y:e.offsetY};if(this.drag){this.cx=this.drag.cx-(e.clientX-this.drag.x)/this.zoom;this.cy=this.drag.cy-(e.clientY-this.drag.y)/this.zoom}this.pick()});c.addEventListener('pointerup',e=>{c.releasePointerCapture(e.pointerId);this.drag=null;this.selected=this.hover});c.addEventListener('dblclick',()=>{if(this.hover){this.navigation.set(this.hover);this.selected=this.hover;this.onDestination?.(this.hover)}})}
 resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);if(this.w!==r.width||this.h!==r.height){this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.w=r.width;this.h=r.height}this.ctx.setTransform(d,0,0,d,0,0)}
 toScreen(x,y){return{x:(x-this.cx)*this.zoom+this.w/2,y:(y-this.cy)*this.zoom+this.h/2}}
 toWorld(x,y){return{x:(x-this.w/2)/this.zoom+this.cx,y:(y-this.h/2)/this.zoom+this.cy}}
 center(){const s=this.getShip();this.cx=s.x;this.cy=s.y}
 adjust(delta){this.zoom=Math.max(.06,Math.min(1.8,this.zoom+delta))}
 pick(){if(!this.w)return;const m=this.toWorld(this.pointer.x,this.pointer.y),objects=[...this.world.locations,this.world.planet,...(this.getTraffic?.().ships||[])];this.hover=objects.map(o=>({...o,d:Math.hypot(o.x-m.x,o.y-m.y)})).sort((a,b)=>a.d-b.d)[0]||null;if(this.hover&&this.hover.d>Math.max(45,24/this.zoom))this.hover=null}
 render(){this.resize();const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#030407';c.fillRect(0,0,this.w,this.h);const drawGrid=(step,color,width)=>{const px=step*this.zoom;if(px<8)return;c.strokeStyle=color;c.lineWidth=width;const sx=((this.w/2-this.cx*this.zoom)%px+px)%px,sy=((this.h/2-this.cy*this.zoom)%px+px)%px;for(let x=sx;x<this.w;x+=px){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.h);c.stroke()}for(let y=sy;y<this.h;y+=px){c.beginPath();c.moveTo(0,y);c.lineTo(this.w,y);c.stroke()}};drawGrid(250,'rgba(120,139,160,.10)',1);drawGrid(1000,'rgba(229,154,47,.24)',1.2);
  for(const a of this.world.asteroids){if(this.zoom<.18&&a.r<23)continue;const p=this.toScreen(a.x,a.y),r=Math.max(1,a.r*this.zoom);if(p.x<-r||p.x>this.w+r||p.y<-r||p.y>this.h+r)continue;c.fillStyle='#6b6257';c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill()}
  for(const t of this.getTraffic?.().ships||[]){const p=this.toScreen(t.x,t.y);c.fillStyle=t.role==='patrol'?'#60a5fa':t.role==='miner'?'#f59e0b':t.role==='vendor'?'#34d399':'#cbd5e1';c.beginPath();c.moveTo(p.x,p.y-5);c.lineTo(p.x+4,p.y+4);c.lineTo(p.x-4,p.y+4);c.closePath();c.fill()}
  for(const o of [...this.world.locations,this.world.planet]){const p=this.toScreen(o.x,o.y),sel=this.navigation.destination?.id===o.id;c.fillStyle=sel?'#f59e0b':o.type==='station'?'#63c8ed':o.type==='quest'?'#fbbf24':'#94a3b8';c.beginPath();c.arc(p.x,p.y,sel?8:5,0,Math.PI*2);c.fill();c.fillStyle='#e5e7eb';c.font='12px sans-serif';c.fillText(`${o.name} [${Math.round(o.x)}, ${Math.round(o.y)}]`,p.x+10,p.y-8)}
  const ship=this.getShip(),sp=this.toScreen(ship.x,ship.y);c.fillStyle='#fff';c.strokeStyle='#38bdf8';c.lineWidth=2;c.beginPath();c.moveTo(sp.x,sp.y-9);c.lineTo(sp.x+7,sp.y+7);c.lineTo(sp.x-7,sp.y+7);c.closePath();c.fill();c.stroke();if(this.navigation.destination){const dp=this.toScreen(this.navigation.destination.x,this.navigation.destination.y);c.strokeStyle='#e59a2f';c.setLineDash([8,7]);c.beginPath();c.moveTo(sp.x,sp.y);c.lineTo(dp.x,dp.y);c.stroke();c.setLineDash([])}
  const cursor=this.toWorld(this.pointer.x,this.pointer.y);c.fillStyle='rgba(3,4,7,.88)';c.fillRect(10,this.h-42,430,30);c.fillStyle='#adb5bf';c.font='12px monospace';c.fillText(`SHIP X ${Math.round(ship.x)} Y ${Math.round(ship.y)} | CURSOR X ${Math.round(cursor.x)} Y ${Math.round(cursor.y)} | ZOOM ${Math.round(this.zoom*100)}%`,20,this.h-22);if(this.hover){c.fillStyle='rgba(8,10,14,.95)';c.strokeStyle='#e59a2f';c.fillRect(12,12,270,78);c.strokeRect(12,12,270,78);c.fillStyle='#f3f4f6';c.font='700 14px sans-serif';c.fillText(this.hover.name||this.hover.role,24,35);c.font='12px sans-serif';c.fillStyle='#aeb6c0';c.fillText(`X ${Math.round(this.hover.x)} · Y ${Math.round(this.hover.y)}`,24,57);c.fillText('Double-click to set destination',24,77)}}
}
