import{COLORS,normalizeExplorer}from'../data/ExplorerOptions.js';
export class AstronautRenderer{
 draw(ctx,x,y,appearance={},options={}){const a=normalizeExplorer(appearance),scale=options.scale||1,dir=options.direction||'down',walk=options.walk||0,body=COLORS[a.suitColor]||COLORS.Azure,accent=COLORS[a.accentColor]||COLORS.White,visor=COLORS[a.visorColor]||COLORS.Cyan,bob=Math.sin(walk*Math.PI*2)*1.5*scale,leg=Math.sin(walk*Math.PI*2)*3*scale;ctx.save();ctx.translate(x,y+bob);ctx.scale(scale,scale);
  ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(4,17,13,6,0,0,Math.PI*2);ctx.fill();
  if(a.backpack!=='Compact'){const pack=ctx.createLinearGradient(-13,-8,-5,12);pack.addColorStop(0,'#61758d');pack.addColorStop(1,'#111c2a');ctx.fillStyle=pack;ctx.strokeStyle='#91a6ba';ctx.lineWidth=1;ctx.fillRect(-12,-9,7,20);ctx.strokeRect(-12,-9,7,20);ctx.fillStyle=accent;ctx.fillRect(-11,-6,2,6)}
  ctx.strokeStyle='#0b1220';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-5,7);ctx.lineTo(-7-leg*.25,18);ctx.moveTo(5,7);ctx.lineTo(7+leg*.25,18);ctx.stroke();ctx.strokeStyle=body;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-5,7);ctx.lineTo(-7-leg*.25,17);ctx.moveTo(5,7);ctx.lineTo(7+leg*.25,17);ctx.stroke();
  const suit=ctx.createLinearGradient(-9,-12,9,11);suit.addColorStop(0,'#eff8ff');suit.addColorStop(.18,body);suit.addColorStop(.68,body);suit.addColorStop(1,'#0b1726');ctx.fillStyle=suit;ctx.strokeStyle='#cde9f7';ctx.lineWidth=1.2;ctx.beginPath();ctx.roundRect(-9,-10,18,22,5);ctx.fill();ctx.stroke();
  ctx.strokeStyle=body;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-7,-5);ctx.lineTo(-13,5+leg*.15);ctx.moveTo(7,-5);ctx.lineTo(13,5-leg*.15);ctx.stroke();ctx.strokeStyle='#dbeafe';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-7,-5);ctx.lineTo(-13,5+leg*.15);ctx.moveTo(7,-5);ctx.lineTo(13,5-leg*.15);ctx.stroke();
  const helmetRadius=a.helmetStyle==='Reinforced'?12:a.helmetStyle==='Compact'?9:10.5;const hg=ctx.createRadialGradient(-4,-20,2,0,-17,helmetRadius);hg.addColorStop(0,'#fff');hg.addColorStop(.28,'#9eb5c9');hg.addColorStop(1,'#27384c');ctx.fillStyle=hg;ctx.strokeStyle=accent;ctx.lineWidth=a.helmetStyle==='Surveyor'?2:1.2;ctx.beginPath();ctx.arc(0,-17,helmetRadius,0,Math.PI*2);ctx.fill();ctx.stroke();
  const faceOffset=dir==='left'?-2:dir==='right'?2:0;const vg=ctx.createRadialGradient(faceOffset-3,-20,1,faceOffset,-17,8);vg.addColorStop(0,'#eaffff');vg.addColorStop(.3,visor);vg.addColorStop(1,'#061522');ctx.fillStyle=vg;ctx.beginPath();ctx.ellipse(faceOffset,-17,7.5,6.5,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.45)';ctx.stroke();
  ctx.fillStyle=accent;ctx.shadowBlur=6;ctx.shadowColor=accent;ctx.fillRect(-4,-2,8,3);ctx.shadowBlur=0;ctx.fillStyle='#07111d';ctx.fillRect(-3,3,6,4);ctx.fillStyle=visor;ctx.fillRect(-2,4,2,1);ctx.restore()}
}
