const VERSION='0.14.0',SAVE='spaceExplorerV014',BASE='/user/themes/quark2-custom/assets/space-explorer/v014/';
const root=document.querySelector('#sl-space-ui-root')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'sl-space-ui-root'}));
document.querySelector('#sl-space-canvas')?.remove();root.innerHTML='<canvas id="se-game"></canvas><div id="se-ui"></div>';
const canvas=document.querySelector('#se-game'),ctx=canvas.getContext('2d'),ui=document.querySelector('#se-ui');
const img={};function load(path){if(!img[path]){const i=new Image();i.src=BASE+path;img[path]=i}return img[path]}
const A=['basalt','cobalt','iron','amber'].map(n=>load(`asteroids/${n}.png`));
const roles=['Explorer','Engineer','Salvager','Pilot'],views=['Front','Side','Back'];
const locations=[{id:'helix',name:'Helix Station',type:'station',x:0,y:0,asset:'stations/helix-station.png',r:180},{id:'neris',name:'Neris',type:'planet',x:-1450,y:-700,asset:'planets/neris.png',r:260},{id:'outpost',name:'Horizon Trade Outpost',type:'outpost',x:1550,y:900,asset:'stations/trade-outpost.png',r:105},{id:'relay',name:'Cobalt Relay',type:'relay',x:900,y:-1350,asset:'stations/communications-relay.png',r:80},{id:'beacon',name:'Broken Signal',type:'mission',x:-1850,y:1200,r:50}];
let state='start',keys={},zoom=.44,last=performance.now(),mapCenter={x:0,y:0},mapZoom=.22,stationPlayer={x:500,y:620},message='';
const fresh=()=>({version:14,name:'Explorer',role:'Explorer',view:'Front',x:360,y:180,vx:0,vy:0,hull:100,shield:100,credits:500,destination:null,mission:{status:'available',stage:0},created:Date.now()});
let save=(()=>{try{return JSON.parse(localStorage.getItem(SAVE))||null}catch{return null}})();
for(const k of Object.keys(localStorage))if(/^secretLabSpace|^spaceExplorer(?!V014)/.test(k))localStorage.removeItem(k);
function persist(){if(save)localStorage.setItem(SAVE,JSON.stringify(save))}
function size(){const d=Math.min(devicePixelRatio||1,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',size);size();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape'&&['map','station'].includes(state))show('flight')});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);addEventListener('wheel',e=>{if(state==='flight')zoom=Math.max(.22,Math.min(.9,zoom-e.deltaY*.0005));if(state==='map')mapZoom=Math.max(.08,Math.min(.5,mapZoom-e.deltaY*.0003))},{passive:true});
function button(label,action,cls=''){return `<button data-action="${action}" class="${cls}">${label}</button>`}
function show(s){state=s;document.body.dataset.seState=s;renderUI()}
function renderUI(){if(state==='start'){ui.innerHTML=`<main class="screen start"><section><small>HELIX COOPERATIVE · EXPEDITION COMMAND · v${VERSION}</small><h1><span>SPACE</span><b>EXPLORER</b></h1><p>A rebuilt expedition. One clean runtime. No legacy assets.</p><div>${button('New Expedition','create','primary')}${save?button('Continue','continue'):''}${button('Reset Data','reset')}</div></section></main>`}
else if(state==='create'){save=save||fresh();ui.innerHTML=`<main class="screen creator"><header><div><small>HELIX EXPLORER REGISTRY</small><h2>Create Pilot</h2></div>${button('Back','start')}</header><section class="creator-grid"><div class="pilot-preview"><img src="${BASE}pilots/${save.role.toLowerCase()}/${save.view.toLowerCase()}.png"><div>${views.map(v=>button(v,`view:${v}`,v===save.view?'active':'')).join('')}</div></div><form id="pilot-form"><label>Explorer name<input name="name" minlength="3" maxlength="18" value="${save.name}" required></label><fieldset><legend>Skill</legend>${roles.map(v=>button(v,`role:${v}`,v===save.role?'active':'')).join('')}</fieldset><p class="role-copy">${{Explorer:'Balanced discovery specialist.',Engineer:'Improved repairs and resilient shields.',Salvager:'More credits from mission salvage.',Pilot:'Higher acceleration and boost efficiency.'}[save.role]}</p><button class="primary launch" type="submit">Launch Expedition</button></form></section></main>`;document.querySelector('#pilot-form').onsubmit=e=>{e.preventDefault();save.name=new FormData(e.currentTarget).get('name').trim();persist();show('flight')}}
else if(state==='flight'){ui.innerHTML=`<div class="hud"><div><b>${save.name}</b><span>${save.role}</span></div><div>SHIELD ${Math.round(save.shield)} · HULL ${Math.round(save.hull)} · CR ${save.credits}</div><div>${button('Map','map')}${button('Save','save')}${button('Home','start')}</div></div><div class="objective">${objective()}</div><div class="hint">WASD fly · wheel zoom · E dock/communicate</div>`}
else if(state==='map'){ui.innerHTML=`<main class="map-ui"><header><div><small>AZURE REACH</small><h2>Tactical Map</h2></div>${button('Return to Flight','flight')}</header><p>Select a location to set or clear a destination. World traffic continues.</p><div class="map-list">${locations.map(l=>button(l.name,`dest:${l.id}`,save.destination===l.id?'active':'')).join('')}</div></main>`}
else if(state==='station'){ui.innerHTML=`<div class="station-hud"><b>HELIX STATION</b><span>WASD move · E interact · Escape undock</span>${button('Undock','flight')}</div><div class="station-message">${message}</div>`}}
function objective(){if(save.mission.status==='available')return 'Dock at Helix Station to accept The Broken Signal.';if(save.mission.status==='active')return 'Mission: investigate the Broken Signal.';return 'The Broken Signal complete. Reward secured.'}
ui.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='create'){save=fresh();show('create')}else if(a==='continue'){show('flight')}else if(a==='reset'){localStorage.clear();save=null;show('start')}else if(a==='start'||a==='flight'||a==='map')show(a);else if(a==='save'){persist();message='Saved.'}else if(a.startsWith('view:')){save.view=a.split(':')[1];renderUI()}else if(a.startsWith('role:')){save.role=a.split(':')[1];renderUI()}else if(a.startsWith('dest:')){const id=a.split(':')[1];save.destination=save.destination===id?null:id;persist();renderUI()}});
function seeded(n){const x=Math.sin(n*91.73+17.1)*43758.5453;return x-Math.floor(x)}
const stars=Array.from({length:520},(_,i)=>({x:seeded(i)*7200-3600,y:seeded(i+800)*7200-3600,r:.4+seeded(i+77)*1.5}));
const rocks=Array.from({length:42},(_,i)=>({x:seeded(i+20)*6200-3100,y:seeded(i+220)*6200-3100,r:28+seeded(i+33)*52,a:seeded(i+55)*6.28,i:i%4})).filter(r=>locations.every(l=>Math.hypot(r.x-l.x,r.y-l.y)>l.r+300));
const traffic=Array.from({length:8},(_,i)=>({a:i*.8,r:420+(i%4)*200,s:.08+(i%3)*.025,role:['patrol','cargo-hauler','maintenance'][i%3]}));
function drawAsset(path,x,y,w,h,rot=0){const im=load(path);if(!im.complete)return;ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore()}
function worldToScreen(x,y,cx=save.x,cy=save.y,z=zoom){return{x:(x-cx)*z+innerWidth/2,y:(y-cy)*z+innerHeight/2}}
function drawSpace(t,mode='flight'){ctx.fillStyle='#010205';ctx.fillRect(0,0,innerWidth,innerHeight);const cx=mode==='map'?mapCenter.x:save.x,cy=mode==='map'?mapCenter.y:save.y,z=mode==='map'?mapZoom:zoom;for(const s of stars){const p=worldToScreen(s.x,s.y,cx,cy,z*.22);if(p.x<0||p.x>innerWidth||p.y<0||p.y>innerHeight)continue;ctx.globalAlpha=.35+.45*Math.sin(t*.001+s.x);ctx.fillStyle='#d9efff';ctx.beginPath();ctx.arc(p.x,p.y,s.r,0,6.29);ctx.fill()}ctx.globalAlpha=1;for(const r of rocks){const p=worldToScreen(r.x,r.y,cx,cy,z);if(p.x<-100||p.x>innerWidth+100||p.y<-100||p.y>innerHeight+100)continue;drawAsset(`asteroids/${['basalt','cobalt','iron','amber'][r.i]}.png`,p.x,p.y,r.r*z*2,r.r*z*2,r.a)}for(const l of locations){const p=worldToScreen(l.x,l.y,cx,cy,z);if(l.asset){const sz=l.r*2*z;drawAsset(l.asset,p.x,p.y,sz,sz)}else{ctx.strokeStyle='#f59e0b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,15,0,6.29);ctx.stroke()}if(mode==='map'||Math.hypot(p.x-innerWidth/2,p.y-innerHeight/2)<500){ctx.fillStyle='#dceeff';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(l.name,p.x,p.y+l.r*z+18)}}for(const tr of traffic){tr.a+=tr.s*.016;const x=Math.cos(tr.a)*tr.r,y=Math.sin(tr.a)*tr.r,p=worldToScreen(x,y,cx,cy,z);drawAsset(`ships/${tr.role}.png`,p.x,p.y,66*z,66*z,tr.a+1.57)}if(save.destination){const l=locations.find(x=>x.id===save.destination);if(l){const a=worldToScreen(save.x,save.y,cx,cy,z),b=worldToScreen(l.x,l.y,cx,cy,z);ctx.strokeStyle='#f59e0b';ctx.setLineDash([9,8]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([])}}}
function nearLocation(){return locations.map(l=>({l,d:Math.hypot(save.x-l.x,save.y-l.y)})).sort((a,b)=>a.d-b.d)[0]}
function updateFlight(dt){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),m=Math.hypot(x,y)||1;save.vx=(save.vx+x/m*260*dt)*.985;save.vy=(save.vy+y/m*260*dt)*.985;const sp=Math.hypot(save.vx,save.vy),max=310;if(sp>max){save.vx=save.vx/sp*max;save.vy=save.vy/sp*max}save.x+=save.vx*dt;save.y+=save.vy*dt;for(const r of rocks){const dx=save.x-r.x,dy=save.y-r.y,d=Math.hypot(dx,dy),min=r.r+34;if(d<min){save.x=r.x+dx/d*min;save.y=r.y+dy/d*min;save.vx*=.55;save.vy*=.55;save.shield=Math.max(0,save.shield-8*dt)}}const n=nearLocation();if(keys.e&&n.d<n.l.r+95){keys.e=0;if(n.l.type==='station'){stationPlayer={x:500,y:640};message=save.mission.status==='available'?'Approach Mission Control to accept The Broken Signal.':'';show('station')}else if(n.l.id==='beacon'&&save.mission.status==='active'){save.mission={status:'complete',stage:2};save.credits+=750;message='Broken Signal decoded. +750 credits.';persist();renderUI()}}}
function drawShip(){drawAsset('ships/player-scout.png',innerWidth/2,innerHeight/2,92,110,Math.atan2(save.vy,save.vx)+1.57)}
function drawMinimap(){const x=innerWidth-210,y=innerHeight-190,w=180;ctx.fillStyle='rgba(2,8,15,.88)';ctx.fillRect(x,y,w,w);ctx.strokeStyle='#2b6788';ctx.strokeRect(x,y,w,w);for(const l of locations){const px=x+w/2+(l.x-save.x)/1800*w/2,py=y+w/2+(l.y-save.y)/1800*w/2;ctx.fillStyle=l.type==='planet'?'#60a5fa':l.type==='mission'?'#f59e0b':'#67e8f9';ctx.beginPath();ctx.arc(px,py,l.type==='planet'?5:3,0,6.29);ctx.fill()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+w/2,y+w/2,4,0,6.29);ctx.fill()}
function drawStation(dt){ctx.fillStyle='#03070d';ctx.fillRect(0,0,innerWidth,innerHeight);const g=ctx.createRadialGradient(innerWidth/2,innerHeight/2,20,innerWidth/2,innerHeight/2,700);g.addColorStop(0,'#12304a');g.addColorStop(1,'#020407');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='rgba(74,170,220,.2)';for(let x=0;x<innerWidth;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=0;y<innerHeight;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}const zones=[{x:innerWidth*.25,y:180,name:'Repair Bay'},{x:innerWidth*.5,y:180,name:'Mission Control'},{x:innerWidth*.75,y:180,name:'Trade Terminal'}];for(const z of zones){ctx.fillStyle='rgba(8,20,32,.9)';ctx.strokeStyle='#2d769e';ctx.fillRect(z.x-100,z.y-50,200,100);ctx.strokeRect(z.x-100,z.y-50,200,100);ctx.fillStyle='#d8efff';ctx.textAlign='center';ctx.fillText(z.name,z.x,z.y+5)}let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);stationPlayer.x=Math.max(30,Math.min(innerWidth-30,stationPlayer.x+dx*220*dt));stationPlayer.y=Math.max(100,Math.min(innerHeight-30,stationPlayer.y+dy*220*dt));const v=Math.abs(dx)>Math.abs(dy)?'side':dy<0?'back':'front';drawAsset(`pilots/${save.role.toLowerCase()}/${v}.png`,stationPlayer.x,stationPlayer.y,70,125);if(keys.e){keys.e=0;const z=zones.map(z=>({...z,d:Math.hypot(stationPlayer.x-z.x,stationPlayer.y-z.y)})).sort((a,b)=>a.d-b.d)[0];if(z.d<150){if(z.name==='Repair Bay'){save.hull=save.shield=100;message='Ship fully repaired.'}if(z.name==='Mission Control'){if(save.mission.status==='available'){save.mission={status:'active',stage:1};save.destination='beacon';message='Mission accepted: The Broken Signal.'}else message=objective()}if(z.name==='Trade Terminal')message='Trade link online. Credits: '+save.credits;persist();renderUI()}}}
function loop(t){const dt=Math.min(.04,(t-last)/1000);last=t;if(state==='flight'){updateFlight(dt);drawSpace(t);drawShip();drawMinimap()}else if(state==='map'){for(const tr of traffic)tr.a+=tr.s*dt;drawSpace(t,'map')}else if(state==='station')drawStation(dt);requestAnimationFrame(loop)}show('start');requestAnimationFrame(loop);
