import{normalizeExplorer,DEFAULT_EXPLORER}from'../data/ExplorerOptions.js';
const INDEX_KEY='secretLabSpaceSlotsV4',PREFIX='secretLabSpaceSlotV4:';
const now=()=>new Date().toISOString();
const clamp=(v,min,max,fallback)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):fallback;
const token=()=>{const bytes=new Uint8Array(10);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(36).padStart(2,'0')).join('').toUpperCase().match(/.{1,5}/g).join('-')};
export const defaults={version:4,slotId:null,recoveryCode:null,explorerName:'Explorer',appearance:structuredClone(DEFAULT_EXPLORER),galaxy:'azure-reach',ship:'kestrel',shipColor:'#7dd3fc',x:245,y:30,shield:100,maxShield:100,hull:100,maxHull:100,boost:100,maxBoost:100,credits:500,cargoCapacity:24,inventory:{scrap:0,iron:0,cobalt:0,electronics:0,fuel:2,components:0},mission:{id:'brokenSignal',stage:0,status:'available'},upgrades:{},destination:null,points:0,playtime:0,createdAt:null,lastSavedAt:null,discovered:['azure-reach'],quests:{main:'broken-signal',stage:0},settings:{quality:'high',fps:60,particles:70,master:.8,music:.6,effects:.8,reducedMotion:false}};
export class SaveSystem{
 list(){try{const ids=JSON.parse(localStorage.getItem(INDEX_KEY)||'[]');return ids.map(id=>this.load(id)).filter(Boolean).sort((a,b)=>(b.lastSavedAt||'').localeCompare(a.lastSavedAt||''))}catch{return[]}}
 existsName(name,except=null){const n=name.trim().toLowerCase();return this.list().some(s=>s.slotId!==except&&s.explorerName.toLowerCase()===n)}
 create(name){name=String(name||'').trim().replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,18);if(name.length<3)throw new Error('Name must contain at least 3 characters.');if(this.list().length>=3)throw new Error('All three save slots are in use.');if(this.existsName(name))throw new Error('This explorer name is already used in another slot.');const id=crypto.randomUUID(),save=this.validate({...defaults,slotId:id,recoveryCode:token(),explorerName:name,createdAt:now(),lastSavedAt:now()});const ids=this.list().map(s=>s.slotId);ids.push(id);localStorage.setItem(INDEX_KEY,JSON.stringify(ids));return this.save(save)}
 load(id){if(!id)return null;try{const raw=localStorage.getItem(PREFIX+id);return raw?this.validate(JSON.parse(raw)):null}catch{return null}}
 validate(v){const d=structuredClone(defaults),s=v&&typeof v==='object'?v:{};return{...d,...s,version:4,slotId:typeof s.slotId==='string'?s.slotId:null,recoveryCode:typeof s.recoveryCode==='string'?s.recoveryCode:null,explorerName:String(s.explorerName||d.explorerName).slice(0,18),appearance:normalizeExplorer(s.appearance),x:clamp(s.x,-9000,9000,0),y:clamp(s.y,-9000,9000,0),shield:clamp(s.shield,0,200,100),maxShield:clamp(s.maxShield,1,200,100),hull:clamp(s.hull,0,200,100),maxHull:clamp(s.maxHull,1,200,100),boost:clamp(s.boost,0,200,100),maxBoost:clamp(s.maxBoost,1,200,100),playtime:clamp(s.playtime,0,1e9,0),settings:{...d.settings,...s.settings}}}
 save(v){const safe=this.validate({...v,lastSavedAt:now()});if(!safe.slotId)throw new Error('Save slot is missing.');localStorage.setItem(PREFIX+safe.slotId,JSON.stringify(safe));return safe}
 delete(id){localStorage.removeItem(PREFIX+id);localStorage.setItem(INDEX_KEY,JSON.stringify(this.list().filter(s=>s.slotId!==id).map(s=>s.slotId)))}
 findByRecovery(code){const c=String(code||'').trim().toUpperCase();return this.list().find(s=>s.recoveryCode===c)||null}
 resetAll(){for(const s of this.list())localStorage.removeItem(PREFIX+s.slotId);localStorage.removeItem(INDEX_KEY)}
}
