import{loadSave,saveGame}from'./save-manager.js';
const c=document.querySelector('#sl-space-canvas');if(c){const x=c.getContext('2d'),keys={},pointer={x:innerWidth/2,y:innerHeight/2};let state=loadSave(),ship={x:state.x||innerWidth/2,y:state.y||innerHeight/2,vx:0,vy:0,a:0},paused=false,lastSave=0;const panel=document.querySelector('#sl-space-panel'),dialog=document.querySelector('#sl-space-dialog');const galaxies={'azure-reach':{name:'Azure Reach',colors:['#020617','#0b3260','#7dd3fc']},'crystal-void':{name:'Crystal Void',colors:['#080414','#35106b','#d8b4fe']},'red-forge':{name:'Red Forge',colors:['#150403','#57170d','#fdba74']},'ancient-horizon':{name:'Ancient Horizon',colors:['#020817','#17366c','#fde68a']},'event-horizon':{name:'Event Horizon',colors:['#010103','#240535','#c4b5fd']}};const ships={kestrel:'Kestrel Scout',viper:'Viper Interceptor',atlas:'Atlas Freighter',aegis:'Aegis Guardian',wraith:'Wraith Phantom'};
 function size(){let d=Math.min(devicePixelRatio||1,state.settings.graphics==='low'?1:1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)}size();addEventListener('resize',size);addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;keys[e.key.toLowerCase()]=1;if(['w','a','s','d',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape'){panel.hidden=true;dialog.hidden=true}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);document.addEventListener('visibilitychange',()=>paused=document.hidden);
 function closeButton(){panel.querySelector('[data-close]')?.addEventListener('click',()=>panel.hidden=true)}
 function save(){state=saveGame({...state,x:ship.x,y:ship.y});lastSave=performance.now()}
 function menu(){panel.hidden=false;panel.replaceChildren();const h=document.createElement('h2');h.textContent='Game menu';const p=document.createElement('p');p.textContent=`Pilot: ${state.pilotName} · ${ships[state.ship]} · ${galaxies[state.galaxy]?.name}`;const saveBtn=document.createElement('button');saveBtn.textContent='Save game';saveBtn.onclick=save;const hangar=document.createElement('button');hangar.textContent='Hangar';hangar.onclick=showHangar;const settings=document.createElement('button');settings.textContent='Settings';settings.onclick=showSettings;const close=document.createElement('button');close.dataset.close='';close.textContent='Close';panel.append(h,p,saveBtn,hangar,settings,close);closeButton()}
 function showHangar(){panel.replaceChildren();const h=document.createElement('h2');h.textContent='Hangar';panel.append(h);for(const [id,name] of Object.entries(ships)){const b=document.createElement('button');b.textContent=(id===state.ship?'✓ ':'')+name;b.onclick=()=>{state.ship=id;state=saveGame(state);showHangar()};panel.append(b)}const close=document.createElement('button');close.dataset.close='';close.textContent='Close';panel.append(close);closeButton()}
 function showSettings(){panel.replaceChildren();const h=document.createElement('h2');h.textContent='Settings';const label=document.createElement('label');label.textContent='Graphics ';const select=document.createElement('select');for(const v of ['auto','high','low']){const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=state.settings.graphics===v;select.append(o)}select.onchange=()=>{state.settings.graphics=select.value;state=saveGame(state);size()};label.append(select);const close=document.createElement('button');close.dataset.close='';close.textContent='Close';panel.append(h,label,close);closeButton()}
 function map(){panel.replaceChildren();const h=document.createElement('h2');h.textContent='Galaxy map';panel.append(h);for(const [id,g] of Object.entries(galaxies)){const b=document.createElement('button');const unlocked=state.discovered.includes(id);b.disabled=!unlocked;b.textContent=(id===state.galaxy?'● ':'')+g.name+(unlocked?'':' · Locked');b.onclick=()=>{state.galaxy=id;state=saveGame(state);document.querySelector('#sl-space-galaxy').textContent=g.name;panel.hidden=true};panel.append(b)}const close=document.createElement('button');close.dataset.close='';close.textContent='Close';panel.append(close);closeButton()}
 document.querySelector('#sl-space-menu').onclick=menu;document.querySelector('#sl-space-map').onclick=map;
 if(state.quests.stage===0){dialog.hidden=false;dialog.textContent='Incoming signal: Explorer, an emergency beacon is broadcasting nearby. Move with WASD and investigate.';setTimeout(()=>{dialog.hidden=true;state.quests.stage=1;state=saveGame(state)},6000)}
 function frame(t){if(!paused){const g=galaxies[state.galaxy]||galaxies['azure-reach'],grad=x.createRadialGradient(innerWidth*.45,innerHeight*.4,20,innerWidth*.45,innerHeight*.4,Math.max(innerWidth,innerHeight));grad.addColorStop(0,g.colors[1]);grad.addColorStop(.65,g.colors[0]);grad.addColorStop(1,'#010208');x.fillStyle=grad;x.fillRect(0,0,innerWidth,innerHeight);for(let i=0;i<180;i++){const a=.2+.5*(.5+.5*Math.sin(t*.001+i));x.fillStyle=`rgba(210,235,255,${a})`;x.fillRect(i*181%innerWidth,i*73%innerHeight,1,1)}let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),m=Math.hypot(dx,dy)||1;ship.vx+=dx/m*.13;ship.vy+=dy/m*.13;ship.vx*=.95;ship.vy*=.95;ship.x=(ship.x+ship.vx+innerWidth)%innerWidth;ship.y=(ship.y+ship.vy+innerHeight)%innerHeight;ship.a=Math.atan2(pointer.y-ship.y,pointer.x-ship.x);x.save();x.translate(ship.x,ship.y);x.rotate(ship.a+Math.PI/2);x.fillStyle=state.shipColor;x.strokeStyle='#e5f7ff';x.lineWidth=1.2;x.shadowBlur=18;x.shadowColor=state.shipColor;x.beginPath();x.moveTo(0,-21);x.lineTo(12,13);x.lineTo(4,8);x.lineTo(0,15);x.lineTo(-4,8);x.lineTo(-12,13);x.closePath();x.fill();x.stroke();x.restore();document.querySelector('#sl-space-coordinates').textContent=`${Math.round(ship.x)}, ${Math.round(ship.y)}`;document.querySelector('#sl-space-health').textContent=`${state.shield} / ${state.hull}`;if(t-lastSave>15000)save()}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
