import{loadSave,saveGame}from'./save-manager.js';
const c=document.querySelector('#sl-space-canvas');if(c){const x=c.getContext('2d'),keys={},pointer={x:innerWidth/2,y:innerHeight/2};let state=loadSave(),player={x:state.x||0,y:state.y||0,vx:0,vy:0,a:0},paused=false,lastSave=0;const panel=document.querySelector('#sl-space-panel'),dialog=document.querySelector('#sl-space-dialog');
 const worlds={
 'azure-reach':{name:'Azure Reach',size:5200,colors:['#020617','#0b3260','#7dd3fc'],places:[['Helix Station',0,0,'station'],['Broken Beacon',900,-650,'quest'],['Cobalt Field',-1250,700,'mine'],['North Gate',1700,-1300,'gate']]},
 'crystal-void':{name:'Crystal Void',size:6200,colors:['#080414','#35106b','#d8b4fe'],places:[['Prism Station',0,0,'station'],['Crystal Scar',1250,500,'mine'],['Echo Ruins',-1500,-900,'quest']]},
 'red-forge':{name:'Red Forge',size:7000,colors:['#150403','#57170d','#fdba74'],places:[['Forge Hub',0,0,'station'],['Pirate Relay',1400,-950,'quest'],['Foundry Belt',-1700,850,'mine']]},
 'ancient-horizon':{name:'Ancient Horizon',size:7800,colors:['#020817','#17366c','#fde68a'],places:[['Archive Gate',0,0,'gate'],['Silent Ring',1600,700,'quest']]},
 'event-horizon':{name:'Event Horizon',size:9000,colors:['#010103','#240535','#c4b5fd'],places:[['Last Light',0,0,'station'],['The Eclipse',2100,-1500,'quest']]}};
 let world=worlds[state.galaxy]||worlds['azure-reach'],stars=Array.from({length:320},(_,i)=>({x:(i*977)%world.size-world.size/2,y:(i*613)%world.size-world.size/2,z:.3+(i%9)/10,p:i*.44}));
 const minimap=document.createElement('canvas');minimap.id='sl-space-minimap';document.body.append(minimap);const mx=minimap.getContext('2d');const objective=document.createElement('div');objective.id='sl-space-objective';document.body.append(objective);
 function objectiveText(){const target=world.places.find(p=>p[3]==='quest')||world.places[0];const dist=Math.round(Math.hypot(target[1]-player.x,target[2]-player.y));objective.textContent=`Objective: Fly to ${target[0]} · ${dist} units`}
 function size(){const d=Math.min(devicePixelRatio||1,state.settings.graphics==='low'?1:1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const md=Math.min(devicePixelRatio||1,1.5);minimap.width=210*md;minimap.height=140*md;mx.setTransform(md,0,0,md,0,0)}size();addEventListener('resize',size);addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;keys[e.key.toLowerCase()]=1;if(['w','a','s','d',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape'){panel.hidden=true;dialog.hidden=true}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);document.addEventListener('visibilitychange',()=>paused=document.hidden);
 function save(){state=saveGame({...state,x:player.x,y:player.y,galaxy:state.galaxy});lastSave=performance.now()}
 function close(){panel.hidden=true}function addClose(){panel.querySelector('[data-close]')?.addEventListener('click',close)}
 function bigMap(){panel.hidden=false;panel.replaceChildren();const h=document.createElement('h2');h.textContent=`Galaxy map · ${world.name}`;const note=document.createElement('p');note.className='sl-map-note';note.textContent='Select an unlocked location to set a navigation target.';const map=document.createElement('div');map.className='sl-map';for(const place of world.places){const b=document.createElement('button');b.textContent=place[0];b.style.left=(50+place[1]/world.size*88)+'%';b.style.top=(50+place[2]/world.size*88)+'%';b.onclick=()=>{state.navTarget={name:place[0],x:place[1],y:place[2]};save();close()};map.append(b)}const you=document.createElement('button');you.textContent='YOU';you.disabled=true;you.style.left=(50+player.x/world.size*88)+'%';you.style.top=(50+player.y/world.size*88)+'%';map.append(you);const closeBtn=document.createElement('button');closeBtn.dataset.close='';closeBtn.textContent='Close';panel.append(h,note,map,closeBtn);addClose()}
 function menu(){panel.hidden=false;panel.innerHTML='<h2>Game menu</h2><button id="sl-resume">Resume</button><button id="sl-save">Save game</button><button id="sl-bigmap">Galaxy map</button><button data-close>Close</button>';panel.querySelector('#sl-resume').onclick=close;panel.querySelector('#sl-save').onclick=save;panel.querySelector('#sl-bigmap').onclick=bigMap;addClose()}
 document.querySelector('#sl-space-menu').onclick=menu;document.querySelector('#sl-space-map').onclick=bigMap;document.querySelector('#sl-space-galaxy').textContent=world.name;
 if(state.quests.stage<2){dialog.hidden=false;dialog.textContent='Mission: locate the Broken Beacon. Use WASD to fly and the map to navigate.';setTimeout(()=>dialog.hidden=true,5500)}
 function drawMini(){mx.clearRect(0,0,210,140);mx.fillStyle='rgba(2,8,20,.9)';mx.fillRect(0,0,210,140);mx.strokeStyle='rgba(125,211,252,.2)';mx.strokeRect(8,8,194,124);for(const p of world.places){mx.fillStyle=p[3]==='quest'?'#fbbf24':p[3]==='station'?'#60a5fa':'#a78bfa';mx.beginPath();mx.arc(105+p[1]/world.size*180,70+p[2]/world.size*112,3,0,Math.PI*2);mx.fill()}mx.fillStyle='#fff';mx.beginPath();mx.arc(105+player.x/world.size*180,70+player.y/world.size*112,3.5,0,Math.PI*2);mx.fill()}
 function frame(t){if(!paused){world=worlds[state.galaxy]||world;const grad=x.createRadialGradient(innerWidth*.45,innerHeight*.4,10,innerWidth*.45,innerHeight*.4,Math.max(innerWidth,innerHeight));grad.addColorStop(0,world.colors[1]);grad.addColorStop(.6,world.colors[0]);grad.addColorStop(1,'#010208');x.fillStyle=grad;x.fillRect(0,0,innerWidth,innerHeight);const zoom=.17;for(const s of stars){const px=(s.x-player.x)*zoom+innerWidth/2,py=(s.y-player.y)*zoom+innerHeight/2;if(px>-5&&px<innerWidth+5&&py>-5&&py<innerHeight+5){x.globalAlpha=.3+.55*(.5+.5*Math.sin(t*.001+s.p));x.fillStyle=world.colors[2];x.fillRect(px,py,1.2*s.z,1.2*s.z)}}x.globalAlpha=1;for(const p of world.places){const px=(p[1]-player.x)*zoom+innerWidth/2,py=(p[2]-player.y)*zoom+innerHeight/2;if(px>-80&&px<innerWidth+80&&py>-80&&py<innerHeight+80){x.strokeStyle=p[3]==='quest'?'#fbbf24':'#60a5fa';x.lineWidth=2;x.beginPath();x.arc(px,py,p[3]==='station'?28:14,0,Math.PI*2);x.stroke();x.fillStyle='#dbeafe';x.font='12px sans-serif';x.textAlign='center';x.fillText(p[0],px,py+42)}}let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),m=Math.hypot(dx,dy)||1;player.vx+=dx/m*.32;player.vy+=dy/m*.32;player.vx*=.94;player.vy*=.94;const max=7,sp=Math.hypot(player.vx,player.vy);if(sp>max){player.vx=player.vx/sp*max;player.vy=player.vy/sp*max}player.x=Math.max(-world.size/2,Math.min(world.size/2,player.x+player.vx));player.y=Math.max(-world.size/2,Math.min(world.size/2,player.y+player.vy));player.a=Math.atan2(pointer.y-innerHeight/2,pointer.x-innerWidth/2);x.save();x.translate(innerWidth/2,innerHeight/2);x.rotate(player.a+Math.PI/2);x.fillStyle=state.shipColor;x.strokeStyle='#e5f7ff';x.lineWidth=1.3;x.shadowBlur=20;x.shadowColor=state.shipColor;x.beginPath();x.moveTo(0,-22);x.lineTo(13,13);x.lineTo(5,8);x.lineTo(0,17);x.lineTo(-5,8);x.lineTo(-13,13);x.closePath();x.fill();x.stroke();x.restore();for(const p of world.places)if(p[3]==='quest'&&Math.hypot(p[1]-player.x,p[2]-player.y)<90&&state.quests.stage<2){state.quests.stage=2;state.points+=500;state.discovered=Array.from(new Set([...state.discovered,'crystal-void']));save();dialog.hidden=false;dialog.textContent='Beacon decoded. Crystal Void has been unlocked. +500 points';setTimeout(()=>dialog.hidden=true,5000)}document.querySelector('#sl-space-coordinates').textContent=`${Math.round(player.x)}, ${Math.round(player.y)}`;document.querySelector('#sl-space-health').textContent=`${state.shield} / ${state.hull}`;drawMini();objectiveText();if(t-lastSave>12000)save()}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
