import{loadSave,saveGame}from'./save-manager.js';
const app=document.querySelector('#sl-space-app');
if(app){
 const panel=document.querySelector('#sl-space-panel');
 const mapBtn=document.querySelector('#sl-space-map');
 const menuBtn=document.querySelector('#sl-space-menu');
 function close(){panel.hidden=true;panel.classList.remove('sl-full-map-panel')}
 document.addEventListener('click',e=>{if(e.target.closest('[data-close],#sl-close-panel,#sl-resume'))close()});
 mapBtn?.addEventListener('click',()=>setTimeout(()=>{panel.classList.add('sl-full-map-panel');const map=panel.querySelector('.sl-map');if(!map)return;let scale=1,ox=0,oy=0,drag=false,lx=0,ly=0;map.style.transformOrigin='center';map.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.65,Math.min(2.5,scale-e.deltaY*.001));map.style.setProperty('--map-scale',scale);map.firstElementChild;map.style.backgroundSize=`${100*scale}% ${100*scale}%`},{passive:false});map.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;map.setPointerCapture(e.pointerId);map.style.cursor='grabbing'});map.addEventListener('pointermove',e=>{if(!drag)return;ox+=e.clientX-lx;oy+=e.clientY-ly;lx=e.clientX;ly=e.clientY;map.style.backgroundPosition=`calc(50% + ${ox}px) calc(50% + ${oy}px)`});map.addEventListener('pointerup',()=>{drag=false;map.style.cursor='grab'})},0));
 menuBtn?.addEventListener('click',()=>setTimeout(()=>{if(!panel||panel.querySelector('#sl-settings-advanced'))return;const s=loadSave();const box=document.createElement('section');box.id='sl-settings-advanced';box.innerHTML=`<h3>Game settings</h3><label>Quality <select data-setting="quality"><option>low</option><option>medium</option><option>high</option><option>ultra</option></select></label><label>FPS limit <select data-setting="fps"><option>30</option><option>60</option><option>90</option><option>120</option></select></label><label>Particles <input data-setting="particles" type="range" min="0" max="100" value="${s.settings.particles??70}"></label><label><input data-setting="nebula" type="checkbox" ${s.settings.nebula!==false?'checked':''}> Nebula effects</label><label><input data-setting="bloom" type="checkbox" ${s.settings.bloom!==false?'checked':''}> Bloom</label><label><input data-setting="shake" type="checkbox" ${s.settings.shake!==false?'checked':''}> Camera shake</label><label><input data-setting="reducedMotion" type="checkbox" ${s.settings.reducedMotion?'checked':''}> Reduced motion</label><h3>Audio</h3><label>Master <input data-setting="master" type="range" min="0" max="100" value="${Math.round((s.settings.master??.8)*100)}"></label><label>Music <input data-setting="music" type="range" min="0" max="100" value="${Math.round((s.settings.music??.6)*100)}"></label><label>Effects <input data-setting="effects" type="range" min="0" max="100" value="${Math.round((s.settings.effects??.8)*100)}"></label>`;panel.append(box);box.querySelector('[data-setting="quality"]').value=s.settings.quality||'high';box.querySelector('[data-setting="fps"]').value=String(s.settings.fps||60);box.addEventListener('change',e=>{const key=e.target.dataset.setting;if(!key)return;const n=loadSave();let value=e.target.type==='checkbox'?e.target.checked:e.target.value;if(['particles','fps'].includes(key))value=Number(value);if(['master','music','effects'].includes(key))value=Number(value)/100;n.settings[key]=value;saveGame(n)})},0));
}
