import{loadSave,SAVE_KEY}from'./save-manager.js';
if(document.body.classList.contains('secret-lab-portal-page')&&!document.querySelector('#secret-lab-locked:not([hidden])')){
 const content=document.querySelector('#secret-lab-content');if(!content||content.hidden){}else{
 const bg=document.createElement('canvas'),shipLayer=document.createElement('canvas');bg.id='sl-mini-space-bg';shipLayer.id='sl-mini-space-ship';document.body.prepend(bg);document.body.append(shipLayer);
 const ui=document.createElement('div');ui.className='sl-mini-actions';ui.innerHTML='<span id="sl-mini-location"></span><button id="sl-mini-control" type="button">Take control</button><a href="/secret-lab/space-explorer">Full game</a>';document.body.append(ui);
 const bx=bg.getContext('2d'),sx=shipLayer.getContext('2d'),keys={},pointer={x:innerWidth*.68,y:innerHeight*.4,inside:true};let save=loadSave(),ship={x:pointer.x,y:pointer.y+scrollY,vx:0,vy:0},control=false,frozen=false,lastMove=performance.now(),vw=innerWidth,vh=innerHeight,docH=vh,stars=[],dust=[],shooters=[];
 const palettes={'azure-reach':['#020617','#0a315c','#071326','#7dd3fc','#2563eb'],'crystal-void':['#080414','#381369','#13082b','#d8b4fe','#7c3aed'],'red-forge':['#160403','#54160c','#1b0706','#fdba74','#dc2626'],'ancient-horizon':['#020817','#16366a','#080f24','#fde68a','#1d4ed8'],'event-horizon':['#010103','#260838','#07010c','#c4b5fd','#581c87']};
 const names={'azure-reach':'Azure Reach','crystal-void':'Crystal Void','red-forge':'Red Forge','ancient-horizon':'Ancient Horizon','event-horizon':'Event Horizon'};
 function refresh(){save=loadSave();document.querySelector('#sl-mini-location').textContent=names[save.galaxy]||'Unknown Space'}refresh();addEventListener('storage',e=>{if(e.key===SAVE_KEY)refresh()});addEventListener('sl-save-updated',refresh);
 function seed(){const count=Math.min(850,Math.max(260,Math.floor(docH/6)));stars=Array.from({length:count},(_,i)=>({x:(i*193+37)%vw,y:(i*131+83)%docH,z:.16+(i%14)/15,p:i*.71}));dust=Array.from({length:45},(_,i)=>({x:(i*251+90)%vw,y:(i*177+40)%docH,r:1+(i%4),a:.025+(i%5)*.012}))}
 function resize(){vw=innerWidth;vh=innerHeight;docH=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,vh);const d=Math.min(devicePixelRatio||1,1.2);for(const [canvas,ctx] of [[bg,bx],[shipLayer,sx]]){canvas.width=Math.round(vw*d);canvas.height=Math.round(docH*d);canvas.style.width=vw+'px';canvas.style.height=docH+'px';ctx.setTransform(d,0,0,d,0,0)}seed();ship.x=Math.max(30,Math.min(vw-30,ship.x));ship.y=Math.max(72,Math.min(docH-30,ship.y))}
 let rt;new MutationObserver(()=>{clearTimeout(rt);rt=setTimeout(resize,180)}).observe(document.body,{childList:true,subtree:true});addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(resize,120)});resize();
 function drawShip(c,type,color){c.fillStyle=color;c.strokeStyle='#e8f8ff';c.lineWidth=1.3;c.shadowBlur=16;c.shadowColor=color;c.beginPath();if(type==='viper'){c.moveTo(0,-20);c.lineTo(17,11);c.lineTo(6,7);c.lineTo(0,16);c.lineTo(-6,7);c.lineTo(-17,11)}else if(type==='atlas'){c.moveTo(-12,-16);c.lineTo(12,-16);c.lineTo(16,12);c.lineTo(7,17);c.lineTo(-7,17);c.lineTo(-16,12)}else if(type==='aegis'){c.arc(0,0,16,0,Math.PI*2);c.moveTo(0,-21);c.lineTo(9,-6);c.lineTo(0,14);c.lineTo(-9,-6)}else if(type==='wraith'){c.moveTo(0,-20);c.quadraticCurveTo(23,2,7,16);c.lineTo(0,8);c.lineTo(-7,16);c.quadraticCurveTo(-23,2,0,-20)}else{c.moveTo(0,-22);c.lineTo(12,11);c.lineTo(5,8);c.lineTo(0,17);c.lineTo(-5,8);c.lineTo(-12,11)}c.closePath();c.fill();c.stroke();c.fillStyle='#dff7ff';c.shadowBlur=4;c.beginPath();c.ellipse(0,-6,3.5,6,0,0,Math.PI*2);c.fill();c.fillStyle=color;c.fillRect(-9,11,4,3);c.fillRect(5,11,4,3)}
 addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY+scrollY;pointer.inside=true;lastMove=performance.now()});document.documentElement.addEventListener('mouseleave',()=>{pointer.inside=false;frozen=true;ship.vx=ship.vy=0});document.documentElement.addEventListener('mouseenter',()=>{pointer.inside=true;frozen=false;pointer.x=ship.x;pointer.y=ship.y;lastMove=performance.now()});addEventListener('blur',()=>{frozen=true;control=false;ship.vx=ship.vy=0;keys.w=keys.a=keys.s=keys.d=0;document.querySelector('#sl-mini-control').textContent='Take control'});addEventListener('focus',()=>{frozen=false;pointer.x=ship.x;pointer.y=ship.y;lastMove=performance.now()});document.addEventListener('visibilitychange',()=>{frozen=document.hidden;if(frozen)ship.vx=ship.vy=0});
 addEventListener('keydown',e=>{if(!control||/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;keys[e.key.toLowerCase()]=1;if(['w','a','s','d'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape'){control=false;document.querySelector('#sl-mini-control').textContent='Take control'}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);document.querySelector('#sl-mini-control').onclick=e=>{control=!control;frozen=false;e.currentTarget.textContent=control?'Release control':'Take control'};
 function frame(t){const p=palettes[save.galaxy]||palettes['azure-reach'],g=bx.createLinearGradient(0,0,vw,docH);g.addColorStop(0,p[0]);g.addColorStop(.45,p[1]);g.addColorStop(1,p[2]);bx.fillStyle=g;bx.fillRect(0,0,vw,docH);for(const q of stars){const a=(.2+q.z*.6)*(.58+.42*Math.sin(t*.0013+q.p));bx.globalAlpha=a;bx.fillStyle=q.z>.72?p[3]:'#e2e8f0';bx.beginPath();bx.arc(q.x,q.y,Math.max(.35,q.z*1.5),0,Math.PI*2);bx.fill()}for(const d of dust){bx.globalAlpha=d.a*(.65+.35*Math.sin(t*.0007+d.x));bx.fillStyle=p[4];bx.beginPath();bx.arc(d.x,d.y,d.r,0,Math.PI*2);bx.fill()}bx.globalAlpha=1;if(!frozen&&Math.random()<.001&&shooters.length<2)shooters.push({x:-80,y:scrollY+Math.random()*vh*.7,vx:7+Math.random()*3,vy:1.5+Math.random()*2,a:1});for(const q of shooters){q.x+=q.vx;q.y+=q.vy;q.a-=.012;bx.globalAlpha=Math.max(0,q.a);bx.strokeStyle=p[3];bx.lineWidth=1.4;bx.beginPath();bx.moveTo(q.x-80,q.y-25);bx.lineTo(q.x,q.y);bx.stroke()}shooters=shooters.filter(q=>q.a>0);bx.globalAlpha=1;sx.clearRect(0,0,vw,docH);
 if(!frozen){if(control){ship.vx+=((keys.d?1:0)-(keys.a?1:0))*.14;ship.vy+=((keys.s?1:0)-(keys.w?1:0))*.14}else{const idle=t-lastMove>2800,tx=idle?vw*.5+Math.sin(t*.0003)*vw*.3:pointer.x,ty=idle?scrollY+vh*.5+Math.cos(t*.00024)*vh*.24:pointer.y;ship.vx+=(tx-ship.x)*.00038;ship.vy+=(ty-ship.y)*.00038}ship.vx*=.958;ship.vy*=.958;const max=control?5:2.8,sp=Math.hypot(ship.vx,ship.vy);if(sp>max){ship.vx=ship.vx/sp*max;ship.vy=ship.vy/sp*max}ship.x=Math.max(25,Math.min(vw-25,ship.x+ship.vx));ship.y=Math.max(70,Math.min(docH-25,ship.y+ship.vy))}
 const sp=Math.hypot(ship.vx,ship.vy);sx.save();sx.translate(ship.x,ship.y);sx.rotate(sp>.03?Math.atan2(ship.vy,ship.vx)+Math.PI/2:0);if(sp>.1){sx.fillStyle=save.shipColor;sx.globalAlpha=.5;sx.beginPath();sx.moveTo(-4,11);sx.lineTo(0,26+sp*3);sx.lineTo(4,11);sx.fill();sx.globalAlpha=1}drawShip(sx,save.ship,save.shipColor);sx.restore();requestAnimationFrame(frame)}requestAnimationFrame(frame)
 }}
